'use client';

import React from 'react';
import { ExportData } from '@/services/exportService';
import styles from './PDFTemplate.module.scss';

interface PDFTemplateProps {
  data: ExportData;
  title?: string;
  children?: React.ReactNode;
}

export default function PDFTemplate({ 
  data, 
  title = 'Social Listening Report',
  children 
}: PDFTemplateProps) {
  return (
    <div className={styles.pdfTemplate}>
      <div className={styles.header}>
        <h1 className={styles.title}>{title}</h1>
        {data.metadata && (
          <div className={styles.metadata}>
            <div className={styles.metadataItem}>
              <span className={styles.label}>Generated:</span>
              <span className={styles.value}>
                {new Date(data.metadata.generatedAt || Date.now()).toLocaleString()}
              </span>
            </div>
            <div className={styles.metadataItem}>
              <span className={styles.label}>Total Records:</span>
              <span className={styles.value}>{data.metadata.totalRecords}</span>
            </div>
            {data.metadata.generatedBy && (
              <div className={styles.metadataItem}>
                <span className={styles.label}>Generated By:</span>
                <span className={styles.value}>{data.metadata.generatedBy}</span>
              </div>
            )}
          </div>
        )}
      </div>

      <div className={styles.content}>
        {children || (
          <div className={styles.summary}>
            <h2>Data Summary</h2>
            <div className={styles.summaryGrid}>
              {data.content && data.content.length > 0 && (
                <div className={styles.summaryCard}>
                  <h3>Social Media Posts</h3>
                  <div className={styles.count}>{data.content.length}</div>
                  <p>Posts analyzed</p>
                </div>
              )}
              {data.hashtags && data.hashtags.length > 0 && (
                <div className={styles.summaryCard}>
                  <h3>Hashtag Metrics</h3>
                  <div className={styles.count}>{data.hashtags.length}</div>
                  <p>Hashtags tracked</p>
                </div>
              )}
              {data.platforms && data.platforms.length > 0 && (
                <div className={styles.summaryCard}>
                  <h3>Platform Metrics</h3>
                  <div className={styles.count}>{data.platforms.length}</div>
                  <p>Platforms analyzed</p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      <div className={styles.footer}>
        <div className={styles.footerContent}>
          <p>Generated by Reputraq Social Listening Platform</p>
          <p className={styles.timestamp}>
            {new Date().toLocaleString()}
          </p>
        </div>
      </div>
    </div>
  );
}
